### ISSUE TITLE
GSoC Checklist

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-webext#1]
Loose tracking of desired features, sorted by easiest first:
- [x] Translating between an existing language pair in the extension pop-up
- [x] Translating a word or phrase that the user hovers on on a website
- [x] Display a hover-on gist for a word, without context
- [x] Translating an entire webpage at a time
- [x] Display a hover-on gist for a word, with context-based translation (requires alignment via word-bound blank)
- [x] Ability to switch between Release and Beta APy
- [x] ...maybe even 3rd party APy for those who have a local/secure installation

Target browsers:
- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] Firefox Android
- [ ] Safari (14+)

**Comment by OverPoweredDev** [comment]
Pop-Up translation is working as of commit https://github.com/apertium/apertium-webext/commit/b57453462a4832d893f7be01589fd04f107cd007. Also it can be switched between Release and Beta at any point since commit https://github.com/apertium/apertium-webext/commit/b9a9d4b056fbc32208179a9ba6eb0c3f0f4514da.

**Comment by OverPoweredDev** [comment]
Hover-On gists are also up after commit https://github.com/apertium/apertium-webext/commit/065c1c99522d7a131325054f0429419f205c5b42

**Comment by OverPoweredDev** [comment]
Webpage translation is complete with 4a428348fb22b3e894a1152952387de7aab3e61d. Chrome and Edge have a few small problems and the firefox popup was fixed after commit 232f33f278b4a05874d36d0796c47cf53616f978

**Comment by OverPoweredDev** [comment]
Context based translation up as of 0f5224c7fd9d4a73760a27088d0e6199659e8f90

The existing hover-tags (now `<span>`'s instead of `<hover>`) work very well with context translation. They're inline tags so they stick to their word in the pipeline and can retain the original meaning through a `data-original` attribute. After that, it's just a bit of parsing and replacement to get contextual translation

**Comment by OverPoweredDev** [comment]
Support for custom Apy's also up since a39167dd7180f989c57f6323f21a2b26d9b005d0

Validity is checked by attempting a listpairs call through the new URL
